### ISSUE TITLE
Seems it is not 100% compatible with React latest version 16.2

### ISSUE THREAD

**Issue by hitendramalviya** [Hardtack/react-mdcw#57]
I am using this in one of my project, & it seems it is not behaving well, I getting below error some times, It was all working fine with no error with React version 15.6.

`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at RippleAdapterImpl.computeBoundingRect (http://localhost:6006/static/preview.bundle.js:164810:41)
    at FoundationAdapter.computeBoundingRect (http://localhost:6006/static/preview.bundle.js:187629:35)
    at Object.object.(anonymous function) [as computeBoundingRect] (http://localhost:6006/static/preview.bundle.js:187648:35)
    at MDCRippleFoundation.layoutInternal_ (http://localhost:6006/static/preview.bundle.js:176465:35)
    at http://localhost:6006/static/preview.bundle.js:176458:17
RippleAdapterImpl.computeBoundingRect @ Ripple.js:138
FoundationAdapter.computeBoundingRect @ adapter.js:86
object.(anonymous function) @ adapter.js:105
layoutInternal_ @ mdc.ripple.js:1140
(anonymous) @ mdc.ripple.js:1133
requestAnimationFrame (async)
layout @ mdc.ripple.js:1132
MDCRippleFoundation._this.resizeHandler_ @ mdc.ripple.js:813
7Ripple.js:138 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at RippleAdapterImpl.computeBoundingRect (http://localhost:6006/static/preview.bundle.js:164810:41)
    at FoundationAdapter.computeBoundingRect (http://localhost:6006/static/preview.bundle.js:187629:35)
    at Object.object.(anonymous function) [as computeBoundingRect] (http://localhost:6006/static/preview.bundle.js:187648:35)
    at MDCRippleFoundation.getFgTranslationCoordinates_ (http://localhost:6006/static/preview.bundle.js:176294:185)
    at MDCRippleFoundation.animateActivation_ (http://localhost:6006/static/preview.bundle.js:176261:42)
    at http://localhost:6006/static/preview.bundle.js:176230:18`

**Comment by hardtack** [comment]
Since React 16, they introduced new context API, and this project does not support it yet.
Maybe this issue is related to that.
I have to modify large set of code to support it...

**Comment by hitendramalviya** [comment]
Would try to contribute & create PR to help you to upgrade this, once I got some spare time.

**Comment by marcofranssen** [comment]
Nice you guys are experiencing same issue. Would be great to have this resolved. @Hardtack do you think this can be done in short timeframe?
